# Cloud Build configuration for McDuck Bank (App Engine)
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Set environment variables for build
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export REACT_APP_FIREBASE_API_KEY=${_FIREBASE_API_KEY}
        export REACT_APP_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}
        export REACT_APP_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}
        export REACT_APP_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}
        export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}
        export REACT_APP_FIREBASE_APP_ID=${_FIREBASE_APP_ID}
        export REACT_APP_USE_FIREBASE_EMULATOR=false
        export REACT_APP_ENABLE_DEBUG=false
        export REACT_APP_ENABLE_ERROR_REPORTING=true
        export NODE_ENV=production
        npm run build

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'app', 'deploy', 
      '--quiet',
      '--promote',
      '--stop-previous-version'
    ]
    env:
      - 'REACT_APP_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'REACT_APP_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - 'REACT_APP_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'

# Substitution variables
substitutions:
  _FIREBASE_API_KEY: 'your-api-key'
  _FIREBASE_AUTH_DOMAIN: 'your-project.firebaseapp.com'
  _FIREBASE_PROJECT_ID: 'your-project-id'
  _FIREBASE_STORAGE_BUCKET: 'your-project.appspot.com'
  _FIREBASE_MESSAGING_SENDER_ID: 'your-sender-id'
  _FIREBASE_APP_ID: 'your-app-id'

# Cloud Build options
options:
  # Use standard machine type (sufficient for React build)
  machineType: 'E2_STANDARD_2'
  
  # Logging options
  logging: CLOUD_LOGGING_ONLY
  
  # Timeout
  timeout: '1200s'